// =========================================
// BILL.JS - COMPLETE UPDATED VERSION
// =========================================


// =========================================
// HELPER FUNCTION
// =========================================

function getNumber(key) {
    const value = parseFloat(localStorage.getItem(key));
    return Number.isFinite(value) ? value : 0;
}

function getJSON(key, fallback = []) {
    try {
        const value = localStorage.getItem(key);

        if (!value) {
            return fallback;
        }

        const parsed = JSON.parse(value);

        return parsed || fallback;

    } catch (error) {

        console.error("JSON error for:", key, error);

        return fallback;
    }
}


// =========================================
// BILL NUMBER
// =========================================

// Bill number is generated by the backend
// when the bill is finally saved.

const billNoElement = document.getElementById("billNo");

if (billNoElement) {

    const savedBillNo =
        localStorage.getItem("savedBillNo");

    billNoElement.textContent =
        savedBillNo || "BILL-NEW";
}


// =========================================
// BILL DATE AND TIME
// =========================================

const billDateElement =
    document.getElementById("billDate");

const billDayTimeElement =
    document.getElementById("billDayTime");

const today = new Date();

const days = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday"
];

let savedDate =
    localStorage.getItem("billDate");

if (!savedDate) {

    savedDate =
        today.getDate().toString().padStart(2, "0") +
        "/" +
        (today.getMonth() + 1)
            .toString()
            .padStart(2, "0") +
        "/" +
        today.getFullYear();

    localStorage.setItem(
        "billDate",
        savedDate
    );
}

if (billDateElement) {

    billDateElement.textContent =
        savedDate;
}

if (billDayTimeElement) {

    const time =
        today.toLocaleTimeString("en-IN", {
            hour: "2-digit",
            minute: "2-digit",
            second: "2-digit",
            hour12: true
        });

    billDayTimeElement.textContent =
        days[today.getDay()] +
        " | " +
        time;
}


// =========================================
// CUSTOMER DETAILS
// =========================================

const customerNameElement =
    document.getElementById("customerName");

const customerMobileElement =
    document.getElementById("customerMobile");

const customerPlaceElement =
    document.getElementById("customerPlace");


if (customerNameElement) {

    customerNameElement.textContent =
        localStorage.getItem("customerName") || "-";
}


if (customerMobileElement) {

    customerMobileElement.textContent =
        localStorage.getItem("customerMobile") || "-";
}


if (customerPlaceElement) {

    customerPlaceElement.textContent =
        localStorage.getItem("customerPlace") || "-";
}


// =========================================
// PAYMENT TYPE
// =========================================

const paymentTypeElement =
    document.getElementById("paymentType");

if (paymentTypeElement) {

    paymentTypeElement.textContent =
        localStorage.getItem("paymentType") || "-";
}


// =========================================
// TOTALS
// =========================================

const woodTotal =
    getNumber("woodTotal");

const othersTotal =
    getNumber("othersTotal");


// Some pages use grandTotal.
// Some old code used finalTotal.
// Support both.

let grandTotal =
    getNumber("grandTotal");

if (grandTotal === 0) {

    grandTotal =
        getNumber("finalTotal");
}


// =========================================
// ADVANCE / BALANCE
// =========================================

const advanceAmount =
    getNumber("advanceAmount");

const balanceAmount =
    getNumber("balanceAmount");


// =========================================
// DISPLAY TOTALS
// =========================================

const woodTotalElement =
    document.getElementById("woodTotal");

const othersTotalElement =
    document.getElementById("othersTotal");

const grandTotalElement =
    document.getElementById("grandTotal");

const advanceAmountElement =
    document.getElementById("advanceAmount");

const balanceAmountElement =
    document.getElementById("balanceAmount");


if (woodTotalElement) {

    woodTotalElement.textContent =
        "₹ " + woodTotal.toFixed(2);
}


if (othersTotalElement) {

    othersTotalElement.textContent =
        "₹ " + othersTotal.toFixed(2);
}


if (grandTotalElement) {

    grandTotalElement.textContent =
        "₹ " + grandTotal.toFixed(2);
}


if (advanceAmountElement) {

    advanceAmountElement.textContent =
        "₹ " + advanceAmount.toFixed(2);
}


if (balanceAmountElement) {

    balanceAmountElement.textContent =
        "₹ " + balanceAmount.toFixed(2);
}


// =========================================
// TABLE REFERENCES
// =========================================

const woodTable =
    document.getElementById("woodTable");

const chargeTable =
    document.getElementById("chargeTable");


// =========================================
// LOAD WOOD DATA
// =========================================

const woodData =
    getJSON("woodData", []);


// =========================================
// DISPLAY WOOD DETAILS
// =========================================

let sno = 1;


if (woodTable) {

    woodData.forEach(function (item) {

        // ---------------------------------
        // If item has no pieces
        // ---------------------------------

        if (
            !item.pieces ||
            !Array.isArray(item.pieces) ||
            item.pieces.length === 0
        ) {

            const row =
                document.createElement("tr");

            const woodName =
                item.woodType === "Other"
                    ? item.otherWood
                    : item.woodType;

            row.innerHTML = `
                <td>${sno}</td>

                <td>
                    ${woodName || "-"}
                </td>

                <td>
                    ${item.breadth || "-"}
                    ×
                    ${item.thickness || "-"}
                </td>

                <td>-</td>

                <td>-</td>

                <td>
                    ${Number(
                        item.totalLength || 0
                    ).toFixed(2)}
                </td>

                <td>
                    ${Number(
                        item.cubicFeet || 0
                    ).toFixed(2)}
                </td>

                <td>
                    ₹ ${Number(
                        item.rate || 0
                    ).toFixed(2)}
                </td>

                <td>
                    ₹ ${Number(
                        item.amount || 0
                    ).toFixed(2)}
                </td>

                <td>
                    ${item.quality || "-"}
                </td>
            `;

            woodTable.appendChild(row);

            sno++;

            return;
        }


        // ---------------------------------
        // Display each piece
        // ---------------------------------

        item.pieces.forEach(
            function (piece, index) {

                const row =
                    document.createElement("tr");


                const length =
                    Number(piece.length || 0) +
                    Number(
                        piece.extraLength || 0
                    );


                // ---------------------------------
                // First row of wood item
                // ---------------------------------

                if (index === 0) {

                    const woodName =
                        item.woodType === "Other"
                            ? item.otherWood
                            : item.woodType;


                    row.innerHTML = `

                        <td>
                            ${sno}
                        </td>

                        <td>
                            ${woodName || "-"}
                        </td>

                        <td>
                            ${item.breadth || "-"}
                            ×
                            ${item.thickness || "-"}
                        </td>

                        <td>
                            ${length}
                        </td>

                        <td>
                            ${piece.qty || 0}
                        </td>

                        <td>
                            ${Number(
                                piece.totalLength || 0
                            ).toFixed(2)}
                        </td>

                        <td>
                            ${Number(
                                item.cubicFeet || 0
                            ).toFixed(2)}
                        </td>

                        <td>
                            ₹ ${Number(
                                item.rate || 0
                            ).toFixed(2)}
                        </td>

                        <td>
                            ₹ ${Number(
                                item.amount || 0
                            ).toFixed(2)}
                        </td>

                        <td>
                            ${item.quality || "-"}
                        </td>
                    `;

                }

                // ---------------------------------
                // Additional piece rows
                // ---------------------------------

                else {

                    row.innerHTML = `

                        <td></td>

                        <td></td>

                        <td></td>

                        <td>
                            ${length}
                        </td>

                        <td>
                            ${piece.qty || 0}
                        </td>

                        <td>
                            ${Number(
                                piece.totalLength || 0
                            ).toFixed(2)}
                        </td>

                        <td></td>

                        <td></td>

                        <td></td>

                        <td></td>
                    `;
                }


                woodTable.appendChild(row);

            }
        );


        sno++;

    });

}


// =========================================
// LOAD OTHER CHARGES
// =========================================

let chargeSno = 1;

const labourCharge =
    getNumber("labourCharge");

const otherCharge =
    getNumber("otherCharge");

const othersData =
    getJSON("othersData", []);

let hasCharge = false;


// =========================================
// LABOUR CHARGE
// =========================================

if (
    chargeTable &&
    labourCharge > 0
) {

    hasCharge = true;

    const row =
        document.createElement("tr");

    row.innerHTML = `

        <td>
            ${chargeSno++}
        </td>

        <td>
            Labour Charge
        </td>

        <td>
            ₹ ${labourCharge.toFixed(2)}
        </td>
    `;

    chargeTable.appendChild(row);
}


// =========================================
// OTHER CHARGE
// =========================================

if (
    chargeTable &&
    otherCharge > 0
) {

    hasCharge = true;

    const row =
        document.createElement("tr");

    row.innerHTML = `

        <td>
            ${chargeSno++}
        </td>

        <td>
            Other Charge
        </td>

        <td>
            ₹ ${otherCharge.toFixed(2)}
        </td>
    `;

    chargeTable.appendChild(row);
}


// =========================================
// ADDITIONAL OTHER CHARGES
// =========================================

if (chargeTable) {

    othersData.forEach(
        function (item) {

            hasCharge = true;

            const row =
                document.createElement("tr");

            row.innerHTML = `

                <td>
                    ${chargeSno++}
                </td>

                <td>
                    ${item.name || "-"}
                </td>

                <td>
                    ₹ ${Number(
                        item.amount || 0
                    ).toFixed(2)}
                </td>
            `;

            chargeTable.appendChild(row);

        }
    );
}


// =========================================
// NO OTHER CHARGES
// =========================================

if (
    chargeTable &&
    !hasCharge
) {

    const row =
        document.createElement("tr");

    row.innerHTML = `

        <td>-</td>

        <td>-</td>

        <td>-</td>
    `;

    chargeTable.appendChild(row);
}


// =========================================
// CFT SUMMARY
// =========================================

const cftSummary = {};


woodData.forEach(
    function (item) {

        let name =
            item.woodType || "Unknown";

        if (
            name === "Other" &&
            item.otherWood
        ) {

            name =
                item.otherWood;
        }


        const cft =
            Number(
                item.cubicFeet || 0
            );


        if (
            Object.prototype.hasOwnProperty
                .call(cftSummary, name)
        ) {

            cftSummary[name] += cft;

        }
        else {

            cftSummary[name] = cft;
        }

    }
);


// =========================================
// DISPLAY CFT SUMMARY
// =========================================

const cftDiv =
    document.getElementById("cftSummary");


if (cftDiv) {

    cftDiv.innerHTML = "";


    for (
        const wood in cftSummary
    ) {

        cftDiv.innerHTML += `

            <p>

                <b>
                    ${wood}
                </b>

                :

                ${cftSummary[wood]
                    .toFixed(2)}

                CFT

            </p>
        `;
    }
}


// =========================================
// PRINT BUTTON
// =========================================

const printBtn =
    document.getElementById("printBtn");


if (printBtn) {

    printBtn.addEventListener(
        "click",
        function () {

            window.print();

        }
    );
}


// =========================================
// BACK BUTTON
// =========================================

const buttons =
    document.querySelectorAll(
        ".buttons button"
    );


if (buttons.length > 0) {

    const backBtn =
        buttons[buttons.length - 1];


    // Do not treat Confirm as Back
    if (
        backBtn &&
        backBtn.id !== "confirmBill" &&
        backBtn.id !== "printBtn"
    ) {

        backBtn.addEventListener(
            "click",
            function () {

                history.back();

            }
        );
    }
}


// =========================================
// AFTER PRINT
// =========================================

window.onafterprint =
    function () {

        console.log(
            "Bill Printed Successfully"
        );

    };


// =========================================
// CONFIRM BILL BUTTON
// =========================================

document.addEventListener(
    "DOMContentLoaded",
    function () {

        const confirmBillBtn =
            document.getElementById(
                "confirmBill"
            );


        if (!confirmBillBtn) {

            console.error(
                "ERROR: Confirm Bill button not found!"
            );

            return;
        }


        console.log(
            "Confirm Bill button found"
        );


        confirmBillBtn.addEventListener(
            "click",
            function () {

                console.log(
                    "CONFIRM BUTTON CLICKED"
                );


                // Go to confirm page
                window.location.href =
                    "confirm.html";

            }
        );

    }
);
