// =========================================
// BILL NUMBER
// =========================================

// Bill number will be generated by MySQL
// after the bill is successfully saved.

const savedBillNo = localStorage.getItem("savedBillNo");

document.getElementById("billNo").textContent =
    savedBillNo || "---";

// =========================================
// Bill Date
// =========================================

const billDate = document.getElementById("billDate");

let savedDate = localStorage.getItem("billDate");

if (savedDate) {

   const now = new Date();

const days = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday"
];

const time =
    now.toLocaleTimeString("en-IN", {
        hour: "2-digit",
        minute: "2-digit",
        second: "2-digit",
        hour12: true
    });

document.getElementById("billDayTime").textContent =
    days[now.getDay()] + " | " + time;

} else {

    const today = new Date();

const days = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday"
];

savedDate =
    today.getDate().toString().padStart(2, "0") + "/" +
    (today.getMonth() + 1).toString().padStart(2, "0") + "/" +
    today.getFullYear();

billDate.textContent = savedDate;

const time =
    today.toLocaleTimeString("en-IN", {
        hour: "2-digit",
        minute: "2-digit",
        second: "2-digit",
        hour12: true
    });

document.getElementById("billDayTime").textContent =
    days[today.getDay()] + " | " + time;

localStorage.setItem("billDate", savedDate);

}


// =========================================
// Customer Details
// =========================================

document.getElementById("customerName").textContent =
    localStorage.getItem("customerName") || "-";

document.getElementById("customerMobile").textContent =
    localStorage.getItem("customerMobile") || "-";

document.getElementById("customerPlace").textContent =
    localStorage.getItem("customerPlace") || "-";


// =========================================
// Totals
// =========================================

const woodTotal =
    parseFloat(localStorage.getItem("woodTotal")) || 0;

const othersTotal =
    parseFloat(localStorage.getItem("othersTotal")) || 0;

const grandTotal =
    parseFloat(localStorage.getItem("finalTotal")) || 0;

document.getElementById("woodTotal").textContent =
    "₹ " + woodTotal.toFixed(2);

document.getElementById("othersTotal").textContent =
    "₹ " + othersTotal.toFixed(2);

document.getElementById("grandTotal").textContent =
    "₹ " + grandTotal.toFixed(2);
    // =========================================
// Advance & Balance Amount
// =========================================



const balanceAmount =
    parseFloat(localStorage.getItem("balanceAmount")) || 0;



document.getElementById("balanceAmount").textContent =
    "₹ " + balanceAmount.toFixed(2);


// =========================================
// Table References
// =========================================

const woodTable =
    document.getElementById("woodTable");

const chargeTable =
    document.getElementById("chargeTable");


// =========================================
// Load Wood Data
// =========================================

const woodData =
    JSON.parse(localStorage.getItem("woodData")) || [];

let sno = 1;// =========================================
// Print Wood Details
// =========================================

woodData.forEach(function(item){

    // Safety check
    if(!item.pieces || item.pieces.length===0){

        const row=document.createElement("tr");

        row.innerHTML=`
            <td>${sno}</td>
            <td>${item.woodType}</td>
            <td>${item.breadth} × ${item.thickness}</td>
            <td>-</td>
            <td>-</td>
            <td>${Number(item.totalLength || 0).toFixed(2)}</td>
            <td>${Number(item.cubicFeet || 0).toFixed(2)}</td>
            <td>₹ ${Number(item.rate || 0).toFixed(2)}</td>
            <td>₹ ${Number(item.amount || 0).toFixed(2)}</td>
            
        `;

        woodTable.appendChild(row);

        sno++;

        return;

    }


    item.pieces.forEach(function(piece,index){

        const row=document.createElement("tr");

        let lengthText = Number(piece.length) + Number(piece.extraLength || 0);
if (index === 0) {

    row.innerHTML = `

        <td>${sno}</td>

        <td>${item.woodType == "Other"
            ? item.otherWood
            : item.woodType}</td>

        <td>${item.breadth} × ${item.thickness}</td>

        <td>${lengthText}</td>

        <td>${piece.qty}</td>

        <td>${Number(piece.totalLength).toFixed(2)}</td>

        <td>${Number(item.cubicFeet).toFixed(2)}</td>

        <td>₹ ${Number(item.rate).toFixed(2)}</td>

        <td>₹ ${Number(item.amount).toFixed(2)}</td>
        <td>${item.quality}</td>

    `;

}
else {

    row.innerHTML = `

        <td></td>

        <td></td>
<td></td>
        <td></td>

        <td>${lengthText}</td>

        <td>${piece.qty}</td>

        <td>${Number(piece.totalLength).toFixed(2)}</td>

        <td></td>

        <td></td>

        <td></td>

    `;

}

woodTable.appendChild(row);

});

sno++;

});// =========================================
// Load Other Charges
// =========================================

// =========================================
// LOAD OTHER CHARGES
// =========================================

let chargeSno = 1;

const labourCharge =
    parseFloat(localStorage.getItem("labourCharge")) || 0;

const otherCharge =
    parseFloat(localStorage.getItem("otherCharge")) || 0;

const othersData =
    JSON.parse(localStorage.getItem("othersData")) || [];

let hasCharge = false;


// =========================================
// LABOUR CHARGE
// =========================================

if (labourCharge > 0) {

    hasCharge = true;

    const row = document.createElement("tr");

    row.innerHTML = `
        <td>${chargeSno++}</td>
        <td>Labour Charge</td>
        <td>₹ ${labourCharge.toFixed(2)}</td>
    `;

    chargeTable.appendChild(row);
}


// =========================================
// OTHER CHARGE
// =========================================

if (otherCharge > 0) {

    hasCharge = true;

    const row = document.createElement("tr");

    row.innerHTML = `
        <td>${chargeSno++}</td>
        <td>Other Charge</td>
        <td>₹ ${otherCharge.toFixed(2)}</td>
    `;

    chargeTable.appendChild(row);
}


// =========================================
// ADDITIONAL OTHER CHARGES
// =========================================

othersData.forEach(function(item) {

    hasCharge = true;

    const row = document.createElement("tr");

    row.innerHTML = `
        <td>${chargeSno++}</td>
        <td>${item.name || "-"}</td>
        <td>₹ ${Number(item.amount || 0).toFixed(2)}</td>
    `;

    chargeTable.appendChild(row);

});


// =========================================
// NO CHARGES
// =========================================

if (!hasCharge) {

    const row = document.createElement("tr");

    row.innerHTML = `
        <td>-</td>
        <td>-</td>
        <td>-</td>
    `;

    chargeTable.appendChild(row);

}

// =========================================
// Print Button
// =========================================

document
.getElementById("printBtn")
.addEventListener("click", function () {

    window.print();

});


// =========================================
// Back Button
// =========================================

const backBtn =
document.querySelector(".buttons button:last-child");

if (backBtn) {

    backBtn.addEventListener("click", function () {

        history.back();

    });

}


// =========================================
// Print Callback
// =========================================

window.onafterprint = function () {

    console.log("Bill Printed Successfully");

};
// ===============================
// CFT Summary
// ===============================

const cftSummary = {};

woodData.forEach(function(item){

    let name = item.woodType;

    if(name === "Other"){
        name = item.otherWood;
    }

    let cft = Number(item.cubicFeet || 0);

    if(cftSummary[name]){

        cftSummary[name] += cft;

    }else{

        cftSummary[name] = cft;

    }

});

const cftDiv = document.getElementById("cftSummary");

for(let wood in cftSummary){

    cftDiv.innerHTML += `
        <p>
            <b>${wood}</b> :
            ${cftSummary[wood].toFixed(2)} CFT
        </p>
    `;

}
// =========================================
// Confirm Bill
// =========================================


document.getElementById("confirmBill").addEventListener("click", function () {

    window.location.href = "../html/confirm.html";

});

